[package]
name = "atlas_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
clap_derive = "4.5.24"
env_logger = "0.11.6"
image = "0.25.5"
log = "0.4.25"
