[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gbase = { path = "../..", features = [] }

[lib]
crate-type = ["rlib", "dylib"]
