[package]
name = "gbase_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
gbase = { path = "../.." }
encase = { version = "0.6.1", features = ["glam"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
fontdue = "0.8.0"
gltf = "1.4.0"
